import { Bot, CreateOfflineOpts, GameApi, cdapi } from "@chronodivide/game-api";
import { Countries } from "@supalosa/chronodivide-bot/dist/bot/logic/common/utils.js";
import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { loadBaselineFactory, InspectableBaselineBot } from "../benchmark/baselineLoader.js";
import { createExperimentManifest } from "../benchmark/provenance.js";
import { withSeededOfflineGame } from "../benchmark/seededOfflineGame.js";
import { createDeployedStrongBotCandidate, InspectableDeployedStrongBot } from "./deployedStrongBotCandidate.js";
import { LITERAL_BUILDING_ELIMINATION_ENDPOINT, LITERAL_BUILDING_ELIMINATION_ENDPOINT_SHA256,
 LITERAL_BUILDING_ELIMINATION_ENDPOINT_VERSION, LiteralBuildingEliminationAdjudicator,
 installLiteralEndpointInstrumentation, snapshotCombatantBuildings } from "./literalBuildingEliminationEndpoint.js";
const COUNTRIES=[Countries.USA,Countries.KOREA,Countries.FRANCE,Countries.GERMANY,Countries.GREAT_BRITAIN,Countries.LIBYA,Countries.IRAQ,Countries.CUBA,Countries.RUSSIA] as const;
const ALLIED=new Set<Countries>(COUNTRIES.slice(0,5));
const MAPS=[{name:"cd_2_tikal.map",sha256:"c4bf8d58d93957aaf7ee1708a956e67bd89e9021b32c240c7bba5cc953ac8ca6"},
{name:"cd_2_peak_of_perfection.map",sha256:"440715dc154ac10b4b922159824140d40c48990311c6838345b66958f3b3a442"}] as const;
const SEED_BASE=4_230_100_000,MAX_TICKS=90_000,SHA=/^[0-9a-f]{64}$/;
const isRecord=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);const fh=(p:string)=>crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");
const reqP=(n:string)=>{const v=process.env[n];if(!v)throw new Error(`${n} required`);return path.resolve(v)};const reqT=(n:string,r:RegExp)=>{const v=process.env[n];if(!v||!r.test(v))throw new Error(`${n} invalid`);return v};
const settings=(mapName:string,candidate:Bot,baseline:Bot,slot:0|1):CreateOfflineOpts=>{const mode=cdapi.getAvailableGameModes(mapName)[0];if(!mode)throw new Error("mode");return{buildOffAlly:false,cratesAppear:false,credits:10_000,gameMode:mode,gameSpeed:6,mapName,mcvRepacks:true,shortGame:false,superWeapons:false,unitCount:0,online:false,agents:slot===0?[candidate,baseline]:[baseline,candidate]};};
const api=(b:InspectableDeployedStrongBot|InspectableBaselineBot,l:string):GameApi=>{if(!b.lastGameApi)throw new Error(`${l} api`);return b.lastGameApi};
type Winner="candidate"|"baseline"|"draw";
const episode=async(factory:Awaited<ReturnType<typeof loadBaselineFactory>>,args:{task:number;mapOrdinal:number;countryOrdinal:number;seedIndex:number;slot:0|1})=>{
 const map=MAPS[args.mapOrdinal],country=COUNTRIES[args.countryOrdinal],seed=SEED_BASE+args.mapOrdinal*90+args.countryOrdinal*10+args.seedIndex;
 const cn=`ProfileCandidate_${args.task}_${args.slot}`,bn=`ProfileBaseline_${args.task}_${args.slot}`;
 const candidate=createDeployedStrongBotCandidate(cn,country),baseline=factory.create(bn,country);const adjudicator=new LiteralBuildingEliminationAdjudicator({candidate:cn,baseline:bn});const {audit}=installLiteralEndpointInstrumentation({candidate,baseline},adjudicator);
 return withSeededOfflineGame(cdapi,settings(map.name,candidate,baseline,args.slot),seed,[{agent:candidate,identity:"candidate"},{agent:baseline,identity:"baseline"}],async game=>{
  const ca=api(candidate,"candidate"),ba=api(baseline,"baseline"),cs=ca.getPlayerData(cn).startLocation,bs=ba.getPlayerData(bn).startLocation;let ticks=0,terminal:any=null,failure:any=null;
  while(ticks<MAX_TICKS&&!terminal&&!failure){adjudicator.beginUpdate(ca);await game.update();ticks++;const stats=game.getPlayerStats(),c=stats.find(x=>x.name===cn),b=stats.find(x=>x.name===bn);if(!c||!b)throw new Error("stats");const x=adjudicator.completeUpdate(ca,{finished:game.isFinished(),defeated:{candidate:c.defeated,baseline:b.defeated}});terminal=x.terminal;failure=x.technicalFailure;}
  if(failure)throw new Error(`endpoint failure ${JSON.stringify(failure)}`);if(audit.forwarded.candidate||audit.forwarded.baseline)throw new Error("quit forwarded");const buildings=snapshotCombatantBuildings(ca,{candidate:cn,baseline:bn});const counts={candidate:buildings.filter(x=>x.owner===cn).length,baseline:buildings.filter(x=>x.owner===bn).length};
  const winner:Winner=terminal?.winner??"draw",status=terminal?.status??"tick_cap_draw";if(winner==="candidate"&&counts.baseline!==0||winner==="baseline"&&counts.candidate!==0)throw new Error("literal mismatch");
  return{schemaVersion:1,endpoint:LITERAL_BUILDING_ELIMINATION_ENDPOINT,endpointVersion:LITERAL_BUILDING_ELIMINATION_ENDPOINT_VERSION,endpointSha256:LITERAL_BUILDING_ELIMINATION_ENDPOINT_SHA256,taskIndex:args.task,mapOrdinal:args.mapOrdinal,mapName:map.name,mapSha256:map.sha256,countryOrdinal:args.countryOrdinal,country,seedIndex:args.seedIndex,requestedEngineSeed:seed,candidateSlot:args.slot,candidateStart:{x:cs.x,y:cs.y},baselineStart:{x:bs.x,y:bs.y},maxTicks:MAX_TICKS,ticks,status,winner,terminalBuildingCounts:counts,quitAttempts:audit.attempts};
 });};
const cell=async()=>{if(process.env.SLURM_JOB_ACCOUNT!=="pi_jss233")throw new Error("account");const task=Number(reqT("TASK_INDEX",/^\d+$/)),out=reqP("OUT_FILE"),program=reqP("PROGRAM_PATH"),protocol=reqP("PROTOCOL_PATH"),gate=reqP("GATE_PATH"),ph=reqT("PROGRAM_SHA256",SHA),rh=reqT("PROTOCOL_SHA256",SHA),gh=reqT("GATE_SHA256",SHA);if(task<0||task>=180||process.env.SLURM_ARRAY_TASK_ID!==String(task)||fs.existsSync(out)||fh(program)!==ph||fh(protocol)!==rh||fh(gate)!==gh||!process.env.BASELINE_PACKAGE_ROOT||process.env.REQUIRE_EXTERNAL_BASELINE!=="true")throw new Error("input");const gv=JSON.parse(fs.readFileSync(gate,"utf8"));if(!isRecord(gv)||gv.status!=="PASS_TEMPERATE_PROFILES_LITERAL_GATE"||gv.passed!==true)throw new Error("gate");
 const repo=execFileSync("git",["rev-parse","--show-toplevel"],{encoding:"utf8"}).trim(),driver=path.join(repo,"packages","chronodivide-bot-driver"),commit=execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();if(execFileSync("git",["branch","--show-current"],{encoding:"utf8"}).trim()!=="main"||execFileSync("git",["status","--short","--untracked-files=no"],{encoding:"utf8"}).trim()!==""||execFileSync("git",["rev-parse","fork/main"],{encoding:"utf8"}).trim()!==commit)throw new Error("source");
 const mapOrdinal=Math.floor(task/90),within=task%90,countryOrdinal=Math.floor(within/10),seedIndex=within%10,map=MAPS[mapOrdinal];if(fh(path.join(driver,"data",map.name))!==map.sha256)throw new Error("map");await cdapi.init(path.join(driver,"data"));const factory=await loadBaselineFactory(path.join(repo,"packages","chronodivide-bot"));
 const manifest=createExperimentManifest({runId:`temperate-profile-pilot-${task}-${process.env.SLURM_JOB_ID}`,mixDir:path.join(driver,"data"),maps:[map.name],effectiveConfig:{task,mapOrdinal,countryOrdinal,seedIndex,slots:[0,1],maxTicks:MAX_TICKS,gateSha256:gh},baseline:factory.descriptor,gameSeedBase:SEED_BASE+mapOrdinal*90+countryOrdinal*10+seedIndex});if(manifest.scheduler.account!=="pi_jss233"||manifest.source.gitCommit!==commit||manifest.source.trackedDirty!==false||manifest.software.baseline.kind!=="external-package"||manifest.software.baseline.trackedDirty!==false)throw new Error("provenance");
 const results=[];for(const slot of [0,1] as const)results.push(await episode(factory,{task,mapOrdinal,countryOrdinal,seedIndex,slot}));const artifact={schemaVersion:1,kind:"temperate-trained-profiles-literal-pilot-cell",status:"COMPLETE_TEMPERATE_PROFILE_PILOT_CELL",complete:true,taskIndex:task,schedulerAccount:"pi_jss233",schedulerJobId:process.env.SLURM_JOB_ID,sourceGitCommit:commit,programSha256:ph,protocolSha256:rh,gateSha256:gh,launchedGameCount:2,manifest,results};fs.writeFileSync(out,JSON.stringify(artifact,null,2)+"\n",{flag:"wx",mode:0o600});console.log(JSON.stringify({status:artifact.status,task}));};
const summarize=(rows:any[])=>{const wins=rows.filter(r=>r.winner==="candidate").length,losses=rows.filter(r=>r.winner==="baseline").length,draws=rows.length-wins-losses;return{games:rows.length,wins,draws,losses,winRate:wins/rows.length};};
const wilsonLower=(wins:number,n:number)=>{const z=1.6448536269514722,p=wins/n,z2=z*z,den=1+z2/n;return(p+z2/(2*n)-z*Math.sqrt(p*(1-p)/n+z2/(4*n*n)))/den;};
const finalize=()=>{if(process.env.SLURM_JOB_ACCOUNT!=="pi_jss233")throw new Error("account");const root=reqP("RESULTS_ROOT"),out=reqP("OUT_FILE"),array=reqT("ARRAY_JOB_ID",/^\d+$/),ph=reqT("PROGRAM_SHA256",SHA),rh=reqT("PROTOCOL_SHA256",SHA),gh=reqT("GATE_SHA256",SHA);if(fs.existsSync(out))throw new Error("exists");const raw=execFileSync("/opt/slurm/current/bin/sacct",["-j",array,"-n","-P","-X","--format=JobID,JobIDRaw,State,ExitCode,Account"],{encoding:"utf8"}),tasks=new Map<number,string>();for(const line of raw.split("\n").filter(Boolean)){const[l,j,s,e,a]=line.split("|"),m=new RegExp(`^${array}_(\\d+)$`).exec(l);if(m&&s==="COMPLETED"&&e==="0:0"&&a==="pi_jss233")tasks.set(Number(m[1]),j);}if(tasks.size!==180)throw new Error(`tasks ${tasks.size}`);const rows:any[]=[];for(let i=0;i<180;i++){const v=JSON.parse(fs.readFileSync(path.join(root,`task-${String(i).padStart(3,"0")}`,"cell.json"),"utf8"));if(v.status!=="COMPLETE_TEMPERATE_PROFILE_PILOT_CELL"||v.taskIndex!==i||String(v.schedulerJobId)!==tasks.get(i)||v.programSha256!==ph||v.protocolSha256!==rh||v.gateSha256!==gh||v.results.length!==2)throw new Error(`cell ${i}`);rows.push(...v.results);}if(rows.length!==360)throw new Error("row count");
 const overall=summarize(rows),maps=Object.fromEntries(MAPS.map(m=>[m.name,summarize(rows.filter(r=>r.mapName===m.name))])),factions={allied:summarize(rows.filter(r=>ALLIED.has(r.country))),soviet:summarize(rows.filter(r=>!ALLIED.has(r.country)))},slots={"0":summarize(rows.filter(r=>r.candidateSlot===0)),"1":summarize(rows.filter(r=>r.candidateSlot===1))},countries=Object.fromEntries(COUNTRIES.map(c=>[c,summarize(rows.filter(r=>r.country===c))])),startLocations=Object.fromEntries(MAPS.map(m=>[m.name,[...new Set(rows.filter(r=>r.mapName===m.name).map(r=>`${r.candidateStart.x},${r.candidateStart.y}`))].sort()]));const lower=wilsonLower(overall.wins,overall.games);const checks={overallLowerAboveHalf:lower>0.5,mapWinsExceedLosses:Object.values(maps).every((x:any)=>x.wins>x.losses),factionWinsExceedLosses:Object.values(factions).every(x=>x.wins>x.losses),slotWinRatesAboveHalf:Object.values(slots).every(x=>x.winRate>0.5),countriesWinsExceedLosses:Object.values(countries).filter((x:any)=>x.wins>x.losses).length>=7,startCoverage:Object.values(startLocations).every(x=>x.length===2)};const passed=Object.values(checks).every(Boolean);const artifact={schemaVersion:1,kind:"temperate-trained-profiles-literal-pilot-finalizer",status:passed?"ADVANCE_TEMPERATE_TRAINED_PROFILES":"FAIL_TEMPERATE_TRAINED_PROFILES",complete:true,passed,schedulerAccount:"pi_jss233",arrayJobId:array,controllerJobId:process.env.SLURM_JOB_ID,sourceGitCommit:rows[0]?JSON.parse(fs.readFileSync(path.join(root,"task-000","cell.json"),"utf8")).sourceGitCommit:null,launchedGameCount:360,overall,oneSided95WilsonLower:lower,maps,factions,slots,countries,startLocations,checks,schedulerJobIds:[...tasks.values()],rows};fs.writeFileSync(out,JSON.stringify(artifact,null,2)+"\n",{flag:"wx",mode:0o600});console.log(JSON.stringify({status:artifact.status,overall,oneSided95WilsonLower:lower,checks}));};
const main=async()=>{const m=reqT("MODE",/^(cell|finalize)$/);if(m==="cell")await cell();else finalize();};const invoked=process.argv[1]?pathToFileURL(path.resolve(process.argv[1])).href:null;if(import.meta.url===invoked)main().catch(e=>{console.error(e);process.exitCode=1;});
